import random

def generate_location():
    # List of Southern Kyrat Locations
    locations = [
        "Rajgad Gulag",
        "Ratu Gadhi",
        "Jalendu Temple",
        "KEO Svargiya Mine",
        "Royal Fortress",
        "Royal Palace",
        "Utkarsh",
        "Bhirabata Outpost",
        "Border Observation Post",
        "KEO Gold Storage",
        "KEO Logging Camp",
        "KEO Pradhana Mine",
        "Lhumtse Barracks",
        "Namboche Monastery",
        "Pokhari Ghara",
        "Royal Guard Kennels",
        "Sahi Jile Checkpoint",
        "Shikharpur",
        "Altar of Kalinag",
        "Anadekhi Ruins",
        "Ananta Muna Shrine",
        "Anjali's Bakery",
        "Asru Cave",
        "Asthi Den",
        "Banashur Ki Sirhi",
        "Banashur's Refuge",
        "Banashur's Tranquility",
        "Bride River Hamlet",
        "Cave of the Dead",
        "Customs Warehousing",
        "Dead Man's Triangle",
        "Devata Re Cave",
        "Devi Temple Ruins",
        "Dhumrapana Shrine",
        "Dolpo Ruins",
        "Drunk Kanak's Truck",
        "Dubaki Cavern",
        "Eagle's Nest",
        "Garma Palana Spring",
        "Garma Springs",
        "Gautami's Retreat",
        "Ghumantu Sherpa Camp",
        "Gornak's Pass",
        "Hima Khoka Cave",
        "Ila's Roost",
        "Jalendu Falls",
        "Jalendu Overlook",
        "Kalesh",
        "Kalinag's Vantage",
        "KEO Logistics",
        "KEO Rija Mine",
        "KEO Scrap Yard",
        "Krolinga Sahida Shrine",
        "Kyra Ki Sansa",
        "Kyra's Humility"
        "Kyra's Shrine",
        "Kyra's Solitude",
        "Lagoon of Tears",
        "Lake Visalakhutta",
        "Lieutenant's Rest",
        "Machali Village",
        "Mansa Market",
        "Ma'untena Ghari Shrine",
        "Medicinal Poachers",
        "Ministry of Public Affairs",
        "Nadi Shrine",
        "Old Kade House",
        "Pathika Shrine",
        "R.A. Confiscation Vault",
        "Raka Ankita Wall",
        "Royal Supply Depot",
        "Royal Vault III",
        "Royal Vault IX",
        "Sadhu Tri Cave",
        "Sapha Pond",
        "Sealed KEO Mine",
        "Sherpa Barpha Camp",
        "Shining Minds Academy",
        "Shining Minds Reformatory",
        "Shining Minds Seminary",
        "Sivira Sherpa Camp",
        "Ska'i Cave",
        "Sky Burial",
        "South Jalendu Checkpoint",
        "Stone Kapa Refuge",
        "Svargiya Takataki Camp",
        "Tarun Matara's Sleep",
        "The Goat's Lair",
        "The Powder Keg Distillery",
        "Thindara Mine",
        "Trethewey Homestead",
        "Trethewey's Cabin",
        "Vidnava's Tent",
        "Visala Shrine",
        "Yalung's Belly",
        "Yathesta Fields",
        "Yugala Rukha Summit",
    ]

    # Select a random location from the list
    random_location = random.choice(locations)
    return random_location

# Generate and print a random location
print(generate_location())
