import random

def generate_location():
    # List of Southern Kyrat Locations
    locations = [
        "Baghadur",
        "Varshakot",
        "Banapur",
        "Chal Jama Monastery",
        "City of Pain",
        "Ghale Homestead",
        "Golden Path Camp",
        "King's Bridge",
        "Kyra Tea Factory",
        "Rochan Brick Factory",
        "Shanath",
        "The Sleeping Saints",
        "Tirtha",
        "Barnali's Textiles",
        "Kheta Manor",
        "Khilana Bazaar",
        "Kyra Tea Terraces",
        "Kyra Tea Weigh Station",
        "Open Hearts Clinic",
        "Pranijagat School",
        "Rochan Brick Co. Shipping",
        "Rochan Brick Co. Storage",
        "Royal Raksi Brewery",
        "Seven Treasures Ashram",
        "Shanath Breeders",
        "Shanath Training Ground",
        "Abandoned Jheel",
        "Aghori Ashram",
        "Arjun's Still",
        "Army Supply Flight 2412",
        "Army Supply Flight 2707",
        "Army Supply Flight 2911",
        "Avinash Primary School",
        "Bagmati Camp",
        "Banashur's Kshetra",
        "Banashur's Pyres",
        "Banashur's Song",
        "Banashur's Tree of Life",
        "Bhutan Ghat",
        "Chinjan Sherpa Camp",
        "Collapsed Ghupa",
        "Cragway Rest",
        "Danger Dashed",
        "Dead End",
        "Deepak's Millet Farm",
        "Dhami Ashram",
        "Dhyangro Ashram",
        "Divya's Hideout",
        "Dochula Tunnel",
        "Dzong Bridge",
        "Dzu-Teh Ruins",
        "Eklo Beindu Summit",
        "Ettan's Shack",
        "Fahmida's House",
        "Gandharva's Radio Station",
        "Ghasa Dhalana Summit",
        "Golden Path Supply Cache",
        "Gre Sikhara Summit",
        "Great Drought Chorten",
        "Hariyo Ghupa",
        "Hariyo Mathi Summit",
        "House of Chiffon",
        "Jhankri Ashram",
        "Kalasa Ashram",
        "Kalinag Returned",
        "Kalinag the Seeker",
        "Kalinag's Descent",
        "Kalinag's Door",
        "Kalinag's Wisdom",
        "Kanan's Farm",
        "Khazana Temple",
        "Khumjung Hamlet",
        "Kyra Tea Farm",
        "Kyra Tea Storage",
        "Kyra's Flower",
        "Kyra's Guidance",
        "Kyra's Meditation",
        "Kyra's Nadi",
        "Kyra's Pilgrimage",
        "Kyra's Refuge",
        "Kyra's Respite",
        "Kyra's Retreat",
        "Kyra's Shade",
        "Kyra's Slumber",
        "Kyra's Tranquility",
        "Kyrat Intl. Airport",
        "Lakeside Sherpa Camp",
        "Malla Bridge",
        "Nadi Gardiyana Summit",
        "Ocean Breeze Lab",
        "Old Isha's House",
        "Oojam's Hut",
        "Prabhakar's Farm",
        "Prabin's House",
        "Pulley Cart",
        "Rai Family House",
        "Raj Pandhi Brewery",
        "Raksi Still",
        "Rato Lagoon",
        "Rochan Brick Co. Offices",
        "Rochan Brick Co. Payroll",
        "Rochan Delivery Wreck",
        "Royal Munitions Depot",
        "Rukha Sikhara Summit",
        "Samapana Falls",
        "Sarbajit's Boat",
        "Sarbajit's Raksi Still",
        "Satish's Sad Room",
        "Shanath Arena",
        "Shanath Hunters",
        "Shanath Poachers",
        "Shanath Proving Ground",
        "Shanath Trappers",
        "Sherpa Forest Camp",
        "Sherpa Plateau Camp",
        "Sherpa Scripture Camp",
        "Sherpa Yak Enclosure",
        "Smuggler's Portage",
        "Sunny & Prem's Storage",
        "Sunny's End",
        "Surefoot Bridge",
        "The church of Longinus",
        "The Crazy Cock Bar",
        "The Partisans' Clinic",
        "Tiger Den",
        "Udayagiri Cave",
        "Vibhat's Auto Repair",
        "Watery Grave",
        "Yakshini's Bondage",
        "Yakshini's Ecstacy",
        "Yakshini's Flesh",
        "Yakshini's Pleasure",
        "Yakshini's Sin",
        "Yalung's Eye",
        "Yalung's Heart",
        "Yalung's Jaw",
        "Yalung's Maw",
        "Yalung's Mind",
        "Yalung's Pantha",
        "Yalung's Rot",
        "Yalung's Seed",
        "Yalung's Skull",
        "Yalung's Soul",
        "Yalung's Spine",
        "Yalung's Stomach",
        "Yalung's Tears",
        "Yalung's Teeth",
    ]

    # Select a random location from the list
    random_location = random.choice(locations)
    return random_location

# Generate and print a random town name
print(generate_location())
